[project]
name = "code_gen"
version = "0.1.0"
description = ""
authors = [{name = "schilkp", email = "schilk.philipp@gmail.com"}]
license = {text = "GPL-3.0-only"}
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[project.optional-dependencies]
dev = ["black>=24.4.2"]
